#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3_ex2(KC_DEL, KC_Q, KC_W, KC_E, KC_R, KC_T, TG(4), TG(6), KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, LSFT_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, TG(5), TG(7), KC_X, KC_H, KC_J, KC_K, KC_L, RSFT_T(KC_CAPS), KC_LCTL, KC_MINS, KC_EQL, KC_Z, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_RCTL, KC_LALT, LT(2,KC_TAB), LT(1,KC_ESC), LT(1,KC_ENT), KC_SPC, KC_RALT),
    [1] = LAYOUT_split_3x6_3_ex2(KC_DEL, KC_AT, KC_LBRC, KC_RBRC, KC_PIPE, KC_AMPR, KC_NO, KC_NO, KC_PERC, KC_GRV, KC_QUOT, KC_DQUO, KC_TILD, KC_BSPC, KC_COLN, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_SCLN, KC_EXLM, KC_LPRN, KC_RPRN, KC_LCBR, KC_RCBR, KC_BSLS, KC_SLSH, KC_CIRC, KC_ASTR, KC_HASH, KC_DLR, KC_QUES, MO(3), KC_TAB, KC_TRNS, KC_TRNS, KC_SPC, MO(3)),
    [2] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_NO, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, KC_DEL, KC_1, KC_2, KC_3, KC_4, KC_G, KC_NO, KC_NO, KC_X, KC_5, KC_6, KC_7, KC_8, KC_ENT, KC_LCTL, KC_MINS, KC_EQL, KC_Z, KC_C, KC_V, KC_C, KC_V, KC_B, KC_COMM, KC_DOT, KC_LCTL, KC_NO, KC_TRNS, KC_NO, KC_RSFT, KC_TAB, KC_NO),
    [3] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS),
    [4] = LAYOUT_split_3x6_3_ex2(KC_NO, UG_HUEU, UG_SATU, UG_VALU, UG_SPDU, KC_NO, TG(4), KC_NO, KC_NO, KC_NO, KC_VOLU, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, UG_PREV, UG_NEXT, KC_NO, UG_TOGG, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, UG_HUED, UG_SATD, UG_VALD, UG_SPDD, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_BRID, KC_NO, KC_NO, KC_NO, KC_TAB, KC_ESC, KC_ENT, KC_SPC, KC_NO),
    [5] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, TG(5), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [6] = LAYOUT_split_3x6_3_ex2(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, TG(6), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, KC_SPC, MO(8), KC_NO, KC_NO, KC_NO),
    [7] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TG(7), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [8] = LAYOUT_split_3x6_3_ex2(KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO)
};

void keyboard_post_init_user() {
    rgb_matrix_mode(RGB_MATRIX_CUSTOM_lucky);
}

// More information for process_record_user
// see https://docs.qmk.fm/custom_quantum_functions#example-process-record-user-implementation
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(2, KC_TAB):
            if (record->tap.count > 0) {
                if (record->event.pressed) {
                    register_code(KC_TAB);
                } else {
                    unregister_code(KC_TAB);
                }
                return false;
            } else {
                if (record->event.pressed) {
                    register_code(KC_LGUI);
                } else {
                    unregister_code(KC_LGUI);
                }
                return true;
            }
        default:
            return true;
    }
}

// More information for rgb_matrix_indicators_advanced_user
// See https://docs.qmk.fm/features/rgb_matrix#indicator-examples
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    if (host_keyboard_led_state().caps_lock) {
        HSV hsv = {0, 255, rgb_matrix_config.hsv.v};
        RGB rgb = hsv_to_rgb(hsv);
        rgb_matrix_set_color_all(rgb.r, rgb.g, rgb.b);
    }
    return false;
}

// More information for get_tapping_term, get_quick_tap_term, get_quick_tap_term and get_hold_on_other_key_press
// See https://docs.qmk.fm/tap_hold for information
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_CAPS):
            return 999;
        case RSFT_T(KC_CAPS):
            return 999;
        case LT(1, KC_ESC):
            return 999;
        case LT(1, KC_ENT):
            return 999;
        default:
            return TAPPING_TERM;
    }
}

uint16_t get_quick_tap_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_CAPS):
            return 50;
        case RSFT_T(KC_CAPS):
            return 50;
        case LT(1, KC_ESC):
            return 50;
        case LT(1, KC_ENT):
            return 50;
        default:
            return QUICK_TAP_TERM;
    }
}

bool get_hold_on_other_key_press(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_CAPS):
            return true;
        case RSFT_T(KC_CAPS):
            return true;
        case LT(1, KC_ESC):
            return true;
        case LT(1, KC_ENT):
            return true;
        default:
            return false;
    }
}

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
